backend:
  name: "github"
  repo: "studio-5-element/website"

media_folder: "content/assets"
public_folder: "/assets"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - { name: "path", label: "Path" }
      - { name: "date", label: "Date", widget: "date" }
      - { name: "title", label: "Title" }
      - { name: "description", label: "Description" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "pages"
    label: "Strony"
    files:
      - label: "Strona Główna"
        name: "home"
        file: "/content/pages/home.md"
        fields:
          - label: "Karuzela"
            name: "carousel"
            widget: "object"
            fields:
              - { name: "secondsForSlide", label: "Czas wyświetlania slajdu [s]", widget: "number", min: 5, max: 20, default: 7 }
              - label: "nakładka"
                name: 'overlay'
                widget: "object"
                fields:
                  - { name: "opacity", label: "Nieprzeźroczystość (0-100) [%]", widget: "number", min: 0, max: 100, default: 10 }
                  - { name: "image", label: "Textura", widget: "image" }
              - label: "slajd"
                name: "slide"
                widget: "list"
                folder: "/content/assets"
                fields:
                  - { name: "image", label: "Tło", widget: "image" }
                  - { name: "displayTextContent", label: "Widoczność tekstu", widget: "boolean", default: false }
                  - { name: "header", label: "Nagłówek", required: false, widget: "string", default: "" }
                  - { name: "description", label: "Opis", required: false, widget: "string", default: "" }
          - label: "O mnie"
            name: "about"
            widget: "object"
            fields:
              - { name: "image", label: "Portret", widget: "image" }
              - { name: "header", label: "Nagłówek", widget: "string", default: "" }
              - { name: "description", label: "Opis", widget: "markdown" }
      - label: "Projekt"
        name: "project"
        file: "/content/pages/project.md"
        fields:
          - label: "Meta-dane Strony"
            name: "pageMetaData"
            widget: "object"
            fields:
              - { name: "title", label: "Tytuł", widget: "string" }
              - { name: "description", label: "Opis", widget: "string" }
          - { name: "title", label: "Tytuł", widget: "string" }
          - { name: "description", label: "Opis", widget: "markdown" }
          - { name: "stepName", label: "Nazwa Kroku", widget: "string" }
          - name: "step"
            label: "Krok"
            widget: "list"
            fields:
              - { name: "title", label: "Nazwa", widget: "string" }
              - { name: "description", label: "Opis", widget: "markdown" }
      - label: "Realizacje"
        name: "caseStudy"
        file: "/content/pages/caseStudy.md"
        fields:
          - label: "Meta-dane Strony"
            name: "pageMetaData"
            widget: "object"
            fields:
              - { name: "title", label: "Tytuł", widget: "string" }
              - { name: "description", label: "Opis", widget: "string" }
          - { name: "title", label: "Tytuł", widget: "string" }
          - name: "section"
            label: "Sekcja"
            widget: "list"
            fields:
              - { name: "title", label: "Nazwa", widget: "string" }
              - { name: "subTitle", label: "Podnazwa", widget: "string" }
              - name: "gallery"
                label: "Galeria"
                widget: "list"
                fields:
                - { name: "image", label: "Obraz", widget: "image" }
                - { name: "alt", label: "Opis", widget: "string" }

